### ISSUE TITLE
Year and date transposed in getUTCDateTime()

### ISSUE THREAD

**Issue by jmpratt** [andrethemac/L76GLNSV4#1]
When I call getUTCDateTime() and print the result, the current date appears behind the "20" and the year is displayed as the date.  For instance, when it's 2018-5-27, that function returns 2027-5-18.

**Comment by andrethemac** [comment]
you're right. my bad. I haven't tested this enough (RMC message are rather rare sometimes). Thanks for mention.

**Comment by jmpratt** [comment]
Happy to help.  Your code is very useful.  Thank you.

**Comment by andrethemac** [comment]
glad you like it.
