### ISSUE TITLE
get_fix timeout does not work

### ISSUE THREAD

**Issue by vinci1it2000** [andrethemac/L76GLNSV4#13]
The timeout does not work, because the `chrono` is continuously reset inside the while loop by `_read_message`.

https://github.com/andrethemac/L76GLNSV4/blob/1cf479b88adf98767afd8459de1f33afcf6fa7ca/L76GNSV4.py#L323

**Comment by dgraposo** [comment]
The same behaviour here! Thanks for the project! Great contribution!

**Comment by andrethemac** [comment]
New commit by Patrick should fix the error. Can you try again?

**Comment by kbondarev** [comment]
I have stumbled on the same issue.

I think in order to fix this you need to create different chrono instances in each function instead of having one instance of chrono in the whole class (self.chrono)

I can attempt and fix this and create a pull request if you want

**Comment by andrethemac** [comment]
Hi everybody. Thank you for the fixed. best regards
