### ISSUE TITLE
UnicodeError when creating the L76 object

### ISSUE THREAD

**Issue by capa89k** [andrethemac/L76GLNSV4#15]
Hello there,

I found a strange error (which I am not able to reproduce), when calling the constructor. It suddenly raised a UnicodeError exception. Currently I am working with a Lopy4 and Pytrack2 board.

As far as I can understand the line of code who produce the unexpected error is the following one:
https://github.com/andrethemac/L76GLNSV4/blob/4904f253267af511cd6513653bb9e52d5829b877/L76GNSV4.py#L229

Even if this is very strange, it seems that I received on the i2c a message that can not be decoded in UTF-8.

For the moment I wrap the initialization in a try/catch block to avoid the firmware to suddenly crash. Do you think it could be a good idea to detect the error inside the constructor? I could provide a PR but the change is very minimal I guess.

Thanks for your nice work.
Best regards.

**Comment by andrethemac** [comment]
Hi. It's been a long time since i've used this library (or the pycom). I should make some time for this. 
You could try to change 'utf-8'  to 'ascii'. Micropython is not as good as python in converting. 
best regards.

**Comment by capa89k** [comment]
Hello there,

I wanted to give you some news about this error, maybe it could be useful to others. The initialization of the module seems to raise an OSError or DecodeError exception (randomly) after a deepsleep (the pycom one not the pytrack one).

I think that this issue is not related to this driver at all. If i deinit the i2c and then I init it again it seems to work again.
