### ISSUE TITLE
Problem with Fipy 1.20.0.rc3 

### ISSUE THREAD

**Issue by x-077** [andrethemac/L76GLNSV4#4]
Hello, 

First thanks for that alternative library, I'm using the following pytrack with Fipy. 

(sysname='FiPy', nodename='FiPy', release='1.20.0.rc3', version='v1.9.4-c5b0b1d on 2018-12-17', machine='FiPy with ESP32', lorawan='1.0.2', sigfox='1.0.1');

Before I switched to your library when using 1.17.x.x, on the first connection after 2 minutes I could get connected to the GPS ( get fix if I can say like that).

Since I upgraded to 1.20.0.rc3 the first connection never happen and it seems to just loop/timeout in the get_fix function. 

I have the same issue with the "offficial" library L76NGSS.py provided on the pycom github.

If you have any hint, thanks by advance. 

Br,

**Comment by andrethemac** [comment]
you can try to put _read_message(self, messagetype='GLL', debug=True) in a loop and see what is comming back from the gps module on the pytrack expansion board. Set debug=True to see the message's.

**Comment by x-077** [comment]
Hello @andrethemac ,

It was a problem between the chair and the keyboard :D 

Sorry. closing the issue.

**Comment by andrethemac** [comment]
:-)
